version: "{build}"
install:
  - gem install rspec --quiet --no-ri --no-rdoc
build: off
test_script:
  - rake
environment:
  matrix:
    - ruby_version: "193"
    - ruby_version: "200"
    - ruby_version: "200-x64"